[
	{
		"code":"F00.00.01.02",
		"content":"运维人员通过账户和密码直接在web端登录",
		"url":"/system/login.htm",
		"param":[
			{
				"name":"userName",
				"title":"用户账号",
				"placeholder":"请输入英文",
				"isRequired":true
			},{
				"name":"password",
				"title":"用户密码",
				"placeholder":"用户密码",
				"isRequired":true
			}
		]
	},
	{
		"code":"F00.00.01.08",
		"content":"代理商通过账户和密码直接在web端登录",
		"url":"/system/agentlogin.htm",
		"param":[
			{
				"name":"userName",
				"title":"用户账号",
				"placeholder":"请输入英文",
				"isRequired":true
			},{
				"name":"password",
				"title":"用户密码",
				"placeholder":"用户密码",
				"isRequired":true
			}
		]
	},
	{
		"code":"F00.00.01.01",
		"content":"医院登录接口，医院登录需要传入医院的域名",
		"url":"/system/hospitalLogin.htm",
		"param":[
			{
				"name":"userName",
				"title":"用户账号",
				"placeholder":"请输入英文",
				"isRequired":true
			},{
				"name":"password",
				"title":"用户密码",
				"placeholder":"用户密码",
				"isRequired":true
			},{
				"name":"origin",
				"title":"域名",
				"placeholder":"域名",
				"isRequired":true
			}
		]
	},
	{
		"code":"F00.00.01.03",
		"content":"所有的外部接口调用一个登出接口。",
		"url":"/system/loginOut.htm",
		"param":[
			{
				"name":"token",
				"title":"token",
				"placeholder":"token",
				"isRequired":true
			}
		]
	}
	
]
