[
 	{
		"code":"F00.00.01.01",
		"content":"医院登录接口，医院登录需要传入医院的域名",
		"url":"/system/hospitalLogin.htm",
		"param":[
			{
				"name":"userName",
				"title":"用户账号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"password",
				"title":"用户密码",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"origin",
				"title":"域名",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.01.02",
		"content":"运维人员、代理商通过账户和密码直接在web端登录",
		"url":"/system/login.htm",
		"param":[
			{
				"name":"userName",
				"title":"用户账号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"password",
				"title":"用户密码",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.01.03",
		"content":"业务员短信验证码登录",
		"url":"/system/businesslogin.htm",
		"param":[
			{
				"name":"mobile",
				"title":"手机号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"code",
				"title":"验证码",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.01.04",
		"content":"获取七牛token",
		"url":"/system/getQn.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.01.05",
		"content":"所有的外部接口调用一个登出接口",
		"url":"/system/loginOut.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.01.06",
		"content":"获取登录用户的菜单信息",
		"url":"/system/usrMenuList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.01.07",
		"content":"获取登录用户的菜单信息",
		"url":"/hospital/doctorMenuList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.02.01",
		"content":"根据查询条件查询医院列表",
		"url":"/hospital/hospitalList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"name",
				"title":"医院名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"organizationType",
				"title":"医院类型",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"medicalInsurance",
				"title":"是否医保:",
				"placeholder":"0否1是",
				"isRequired":false
			},{
				"name":"provId",
				"title":"所在省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"所在市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"districtId",
				"title":"所在县",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"latitude",
				"title":"纬度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"longitude",
				"title":"经度",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"sort",
				"title":"排列方式",
				"placeholder":"距离最近 favourite 收藏最多 order 就诊最多",
				"isRequired":false
			},{
				"name":"createDateStart",
				"title":"开通开始时间",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"createDateEnd",
				"title":"开通结束时间",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"internalBusinessPeopleId",
				"title":"导医业务员",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"status",
				"title":"状态",
				"placeholder":"0:正常;1:已下架",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.02.02",
		"content":"根据查询条件查询医院信息及其分佣信息",
		"url":"/hospital/hospitalInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"医院ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.02.03",
		"content":"根据查询条件查询医院信息及其分佣信息。",
		"url":"/system/getInternalList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"name",
				"title":"姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"mobile",
				"title":"手机号",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.02.04",
		"content":"根据查询条件查询医院信息及其分佣信息。",
		"url":"/system/getInternalInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"商务人士ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.02.05",
		"content":"对医院信息新增或者修改：当有医院ID时为修改，否则为新增。",
		"url":"/hospital/saveHospital.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"医院ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"internalBusinessPeopleId",
				"title":"内部业务员ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"医院名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"domainName",
				"title":"登录域名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"medicalInsurance",
				"title":"是否医保",
				"placeholder":"0：不是,1：是",
				"isRequired":false
			},{
				"name":"organizationType",
				"title":"医院类型",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"provId",
				"title":"省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"districtId",
				"title":"分布区",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"address",
				"title":"详细地址",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"trafficRoute",
				"title":"交通线路",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"longitude",
				"title":"经度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"latitude",
				"title":"维度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"managerName",
				"title":"医院His管理人员名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"managerMobile",
				"title":"管理员手机号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"managerEmail",
				"title":"管理员邮箱",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"contactMobile",
				"title":"联系电话",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"introduction",
				"title":"医院简介",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"icon",
				"title":"图标",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"images",
				"title":"图片列表",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"monthlyMessagePlanCount",
				"title":"每月计划群发次数",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"monthlyMessageActualCount",
				"title":"每月实际群发总数",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registrationContactName",
				"title":"医院联系人姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registrationContactMobile",
				"title":"医院联系人电话",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registrationContactEmail",
				"title":"医院联系人邮箱",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"drugFeePercent",
				"title":"药费佣金比例",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"treatmentFeePercent",
				"title":"诊疗费佣金比例",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"receptionFee",
				"title":"接洽费",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientSharePercent",
				"title":"患者补贴比例",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"primarySalesmanSharePercent",
				"title":"一级业务员奖金比例",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"secondarySalesmanSharePercent",
				"title":"二级业务员奖金比例",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"organizationSharePercent",
				"title":"医院共享用户分佣比例",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"platformSharePercent",
				"title":"平台佣金比例",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"bankName",
				"title":"银行名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"bankAccountName",
				"title":"银行账户名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"bankAccountNumber",
				"title":"银行账号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"status",
				"title":"状态",
				"placeholder":"0正常1异常",
				"isRequired":false
			},{
				"name":"createDate",
				"title":"创建时间",
				"placeholder":"格式：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"currentBalance",
				"title":"账户余额",
				"placeholder":"冗余字段可不填写",
				"isRequired":false
			},{
				"name":"initialUsername",
				"title":"初始账号",
				"placeholder":"初始账号",
				"isRequired":false
			},{
				"name":"initialPassword",
				"title":"初始密码",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.02.06",
		"content":"医院保存本医院信息所以不需要传入id以及name",
		"url":"/hospital/saveMyHospital.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"address",
				"title":"地址",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"provId",
				"title":"省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"districtId",
				"title":"区",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"contactMobile",
				"title":"联系电话",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"icon",
				"title":"图标",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"introduction",
				"title":"介绍",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"trafficRoute",
				"title":"路线",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"images",
				"title":"图片",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.02.07",
		"content":"根据填写的医院地址去外部地图系统（高德）中获取经纬度信息",
		"url":"/hospital/getLocation.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"address",
				"title":"详细地址",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.02.08",
		"content":"app接口：参数为医生名称，关联查询出有这个医生的医院列表",
		"url":"/hospital/docHospitalList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"provId",
				"title":"省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"latitude",
				"title":"纬度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"longitude",
				"title":"经度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"名称",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"sort",
				"title":"排列方式",
				"placeholder":"距离最近 favourite 收藏最多 order 就诊最多",
				"isRequired":false
			},{
				"name":"organizationType",
				"title":"医院类型",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"medicalInsurance",
				"title":"是否医保",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.02.09",
		"content":"app接口：参数为科室名称，关联查询出有这个科室的医院列表",
		"url":"/hospital/depHospitalList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"provId",
				"title":"省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"latitude",
				"title":"纬度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"longitude",
				"title":"经度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"名称",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"sort",
				"title":"排列方式",
				"placeholder":"距离最近 favourite 收藏最多 order 就诊最多",
				"isRequired":false
			},{
				"name":"organizationType",
				"title":"医院类型",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"medicalInsurance",
				"title":"是否医保",
				"placeholder":"0是1不是",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.05.01",
		"content":"查询角色列表信息",
		"url":"/hospital/roleList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.05.02",
		"content":"新增或修改角色信息接口：当角色ID为空时新增，不为空时修改",
		"url":"/hospital/saveRole.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"角色id",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"organizationId",
				"title":"医院ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"角色名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"locked",
				"title":"是否可编辑",
				"placeholder":"0可以1不可以",
				"isRequired":false
			},{
				"name":"status",
				"title":"状态",
				"placeholder":"0,正常;1,异常",
				"isRequired":false
			},{
				"name":"createDate",
				"title":"创建时间",
				"placeholder":"格式：yyyy-mm-dd",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.05.03",
		"content":"根据医生ID删除角色信息",
		"url":"/hospital/delRole.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"角色ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.06.01",
		"content":"查询岗位列表信息",
		"url":"/hospital/jobList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"roleId",
				"title":"角色ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.06.02",
		"content":"新增或修改岗位信息接口：当岗位ID为空时新增，不为空时修改",
		"url":"/hospital/saveJob.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"岗位id",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"roleId",
				"title":"角色id",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"岗位名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"locked",
				"title":"是否可编辑",
				"placeholder":"0可以1不可以",
				"isRequired":false
			},{
				"name":"status",
				"title":"状态",
				"placeholder":"0正常,1不正常",
				"isRequired":false
			},{
				"name":"createDate",
				"title":"创建时间",
				"placeholder":"格式：yyyy-mm-dd",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.06.03",
		"content":"根据岗位ID删除岗位信息",
		"url":"/hospital/delJob.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"岗位ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.07.01",
		"content":"查询所有菜单信息",
		"url":"/hospital/getMenuList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.07.02",
		"content":"根据岗位ID查询菜单列表",
		"url":"/hospital/getJobMenuList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"岗位ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.07.03",
		"content":"保存岗位菜单信息",
		"url":"/hospital/saveJobMenu.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"岗位ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"menuIds",
				"title":"菜单id",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.07.04",
		"content":"根据岗位ID以及菜单ID删除关系信息",
		"url":"/hospital/delJobMenu.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"jobTitleId",
				"title":"岗位ID",
				"placeholder":"请输入岗位ID",
				"isRequired":false
			},{
				"name":"menuIds",
				"title":"菜单ID",
				"placeholder":"请输入菜单ID",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.10.01",
		"content":"该接口查询条件冗余了一些字段，外部调用时用不到的可不用关注",
		"url":"/order/orderList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"outpatientStatus",
				"title":"就诊状态",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registerStatus",
				"title":"预约状态",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientName",
				"title":"患者姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientMobile",
				"title":"患者手机号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registerStartDate",
				"title":"预约开始时间",
				"placeholder":"格式:yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"registerEndDate",
				"title":"预约结束时间",
				"placeholder":"格式:yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"doctorName",
				"title":"医生姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientSource",
				"title":"患者来源",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registerType",
				"title":"类型",
				"placeholder":"0：app代约，1：微信预约",
				"isRequired":false
			},{
				"name":"previousRegistration",
				"title":"复诊状态",
				"placeholder":"0：复诊，1：非复诊",
				"isRequired":false
			},{
				"name":"agentMobile",
				"title":"代约人手机号",
				"placeholder":"代约人手机号",
				"isRequired":false
			},{
				"name":"organizationName",
				"title":"医院名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.10.02",
		"content":"根据登录的业务员获取预约列表",
		"url":"/order/agentOrderList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"outpatientStatus",
				"title":"就诊状态",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registerStatus",
				"title":"预约状态",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.10.03",
		"content":"业务员新增口预约信息",
		"url":"/order/busSaveOrder.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"organizationId",
				"title":"医院ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"departmentId",
				"title":"科室ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"shiftPlanId",
				"title":"排班ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"shiftPeriodId",
				"title":"排班时间ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorId",
				"title":"医生ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientName",
				"title":"患者姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientMobile",
				"title":"手机号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientGender",
				"title":"性别",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientAge",
				"title":"年龄",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registerDate",
				"title":"预约时间",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.10.04",
		"content":"业务员修改预约信息",
		"url":"/order/editBusOrder.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"registrationId",
				"title":"预约ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"departmentId",
				"title":"科室ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"shiftPlanId",
				"title":"排班ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"shiftPeriodId",
				"title":"排班时间ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorId",
				"title":"医生ID",
				"placeholder":"医生ID",
				"isRequired":false
			},{
				"name":"registerDate",
				"title":"预约时间",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.10.05",
		"content":"医院新增收费患者信息接口",
		"url":"/order/hosSaveOrder.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"patientName",
				"title":"患者姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientMobile",
				"title":"患者手机",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientGender",
				"title":"性别",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientAge",
				"title":"年龄",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientSource",
				"title":"来源",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"treatmentFee",
				"title":"诊疗费",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"drugFee",
				"title":"药费",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"departmentId",
				"title":"接待科室",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorId",
				"title":"接待医生",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"comment",
				"title":"备注",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"regDepartmentId",
				"title":"复诊科室",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"regDoctorId",
				"title":"复诊医生",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registerDate",
				"title":"复诊日期",
				"placeholder":"格式：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"shiftPeriodId",
				"title":"复诊时段ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"shiftPlanId",
				"title":"所选复诊排班ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"description",
				"title":"描述",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.10.06",
		"content":"根据预约ID取消预约信息",
		"url":"/order/cancelOrder.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"预约ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.10.07",
		"content":"收费操作",
		"url":"/order/visit.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"registrationId",
				"title":"预约ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"departmentId",
				"title":"科室ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorId",
				"title":"医生ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"treatmentFee",
				"title":"诊疗费",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"drugFee",
				"title":"药费",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"comment",
				"title":"备注",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"regDepartmentId",
				"title":"复诊科室",
				"placeholder":"可为空",
				"isRequired":false
			},{
				"name":"regDoctorId",
				"title":"复诊医生",
				"placeholder":"可为空",
				"isRequired":false
			},{
				"name":"registerDate",
				"title":"复诊日期",
				"placeholder":"可为空",
				"isRequired":false
			},{
				"name":"shiftPeriodId",
				"title":"复诊时段ID",
				"placeholder":"可为空",
				"isRequired":false
			},{
				"name":"shiftPlanId",
				"title":"所选复诊排班ID",
				"placeholder":"可为空",
				"isRequired":false
			},{
				"name":"description",
				"title":"描述",
				"placeholder":"可为空",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.10.08",
		"content":"查询收费信息",
		"url":"/order/orderInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"预约ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},
	{
		"code":"F00.00.10.09",
		"content":"查询收费信息",
		"url":"/order/orderInfoBySerialNumber.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"serialNumber",
				"title":"流水号",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.12.01",
		"content":"根据条件查询出所有评价列表（如果是医院查询需自动增加医院条件过滤）",
		"url":"/operate/evaluateList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},
			{
				"name":"patientId",
				"title":"患者ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientName",
				"title":"患者姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorName",
				"title":"医生姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorScore",
				"title":"医生评分",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"organizationName",
				"title":"医院名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"organizationScore",
				"title":"医院评分",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"createDateStart",
				"title":"评价时间(开始) ",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"createDateEnd",
				"title":"评价时间（结束）",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"replied",
				"title":"是否回复",
				"placeholder":"0否1是",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.12.02",
		"content":"添加回复评价信息",
		"url":"/operate/addReplyEvaluate.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"用户口令",
				"isRequired":true
			},{
				"name":"id",
				"title":"评价id",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"repliedContent",
				"title":"回复内容",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.12.03",
		"content":"根据评价id查看评价信息详情",
		"url":"/operate/evaluateInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"评价id",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.13.01",
		"content":"获取患者反馈列表",
		"url":"/operate/patientFeedbackList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"userId",
				"title":"患者id",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"createDateStart",
				"title":"添加反馈时间(开始)",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"createDateEnd",
				"title":"添加反馈时间（结束）",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"replied",
				"title":"是否回复",
				"placeholder":"（1是，2否）",
				"isRequired":false
			},{
				"name":"patientName",
				"title":"患者姓名",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.13.02",
		"content":"获取宣传员反馈列表",
		"url":"/operate/agentFeedbackList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"apiId",
				"title":"患者id",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"createDateStart",
				"title":"添加反馈时间(开始) ",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"createDateEnd",
				"title":"添加反馈时间（结束）",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"replied",
				"title":"是否回复",
				"placeholder":"（1是，2否）",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.13.03",
		"content":"增加反馈信息",
		"url":"/operate/addFeedback.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"medicalRecordId",
				"title":"预约ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"feedbackContent",
				"title":"反馈内容",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"images",
				"title":"文件编号",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.13.04",
		"content":"添加回复反馈信息",
		"url":"/operate/addReplyFeedback.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"意见反馈ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"repliedContent",
				"title":"回复信息",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.13.05",
		"content":"查看反馈详情",
		"url":"/operate/feedbackInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"意见反馈ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.19.01",
		"content":"获取业绩管理列表",
		"url":"/finance/getAchievementList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"reservedProvId",
				"title":"省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"reservedCityId",
				"title":"市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"reservedRelateToTeamName",
				"title":"所属组织名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示条数",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.19.02",
		"content":"查看单个代理商的业绩统计",
		"url":"/finance/getAchievementInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"pageSize",
				"title":"每页显示条数",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"id",
				"title":"代理商ID",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"filterKey",
				"title":"筛选参数",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"filterStartDate",
				"title":"filterStartDate",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"filterEndDate",
				"title":"filterEndDate",
				"placeholder":"",
				"isRequired":false
			}
		]
	},
	{
		"code":"F00.00.19.03",
		"content":"代理商--员工业绩统计",
		"url":"/finance/getBusinessCount.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"pageSize",
				"title":"每页显示条数",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"name",
				"title":"业务员名称",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"mobile",
				"title":"业务员手机号",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"filterKey",
				"title":"筛选参数",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"filterStartDate",
				"title":"filterStartDate",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"filterEndDate",
				"title":"filterEndDate",
				"placeholder":"",
				"isRequired":false
			}
		]
	},
	{
		"code":"F00.00.19.04",
		"content":"代理商--下线业务统计",
		"url":"/finance/getDirectBusinessCount.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"pageSize",
				"title":"每页显示条数",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"name",
				"title":"业务员名称",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"mobile",
				"title":"业务员手机号",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"filterKey",
				"title":"筛选参数",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.21.01",
		"content":"根据查询条件查询消息列表",
		"url":"/operate/newsList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.21.02",
		"content":"根据科室ID查询消息详细信息",
		"url":"/operate/newsInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"消息ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.21.03",
		"content":"根据科室ID查询消息详细信息",
		"url":"/operate/addNews.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"title",
				"title":"标题",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"content",
				"title":"内容",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.22.01",
		"content":"根据查询条件查询资讯列表",
		"url":"/operate/informationList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"pageIndex",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"author",
				"title":"作者",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"发布范围-市",
				"placeholder":"-市",
				"isRequired":false
			},{
				"name":"provId",
				"title":"发布范围-省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"createDateStart",
				"title":"发布时间-开始",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"createDateEnd",
				"title":"发布时间-结束",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"creatorName",
				"title":"发布人",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"isNanner",
				"title":"是否设置banner",
				"placeholder":"(0:否;1:是)",
				"isRequired":false
			},{
				"name":"type",
				"title":"资讯类型",
				"placeholder":"(0:健康养生;1:医疗知识;2:最新资讯;3:平台活动;4:天使导医)",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.22.02",
		"content":"根据科室ID查询资讯详细信息",
		"url":"/operate/informationInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"咨询ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.22.03",
		"content":"新增或修改资讯信息接口：当资讯ID为空时新增，不为空时修改",
		"url":"/operate/addInformation.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},
			{
				"name":"id",
				"title":"资讯ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"type",
				"title":"类型",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"provId",
				"title":"省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"title",
				"title":"标题",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"author",
				"title":"作者",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"icon",
				"title":"图标",
				"placeholder":"图标",
				"isRequired":false
			},{
				"name":"digest",
				"title":"摘要",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"content",
				"title":"内容",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"isBanner",
				"title":"是否设置为Banner",
				"placeholder":"(0:否;1:是)",
				"isRequired":false
			},{
				"name":"bannerIcon",
				"title":"banner图标",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"bannerStartDate",
				"title":"banner开始时间",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"bannerEndDate",
				"title":"banner结束时间",
				"placeholder":"格式为：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"pageRead",
				"title":"访问次数",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.22.04",
		"content":"根据科室ID删除资讯信息",
		"url":"/operate/deleteInformation.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"咨询ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},
	{
		"code":"F00.00.22.05",
		"content":"获取banner列表",
		"url":"/operate/getBannerList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.26.01",
		"content":"根据查询条件查询账户列表",
		"url":"/system/getUserList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"actualName",
				"title":"用户姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"用户账号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.26.02",
		"content":"根据科室ID查询账户详细信息",
		"url":"/system/userInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"用户ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.26.03",
		"content":"新增或修改账户信息接口：当账户ID为空时新增，不为空时修改",
		"url":"/system/saveUserInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"账号ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"登录名",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"password",
				"title":"密码",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"actualName",
				"title":"姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"createDate",
				"title":"创建时间",
				"placeholder":"格式：yyyy-mm-dd",
				"isRequired":false
			},{
				"name":"portalRoleId",
				"title":"角色ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"roleName",
				"title":"角色",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"roleIsAdmin",
				"title":"是否为管理员",
				"placeholder":"0是1不是",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.26.04",
		"content":"根据科室ID删除账户信息",
		"url":"/system/delUserInfo.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"账号ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.26.05",
		"content":"获取所有频道列表",
		"url":"/system/getChannelList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.26.06",
		"content":"获取所有角色列表",
		"url":"/system/getRolelList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.26.07",
		"content":"根据角色id获取频道列表",
		"url":"/system/getRoleChannelList.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"portalRoleId",
				"title":"角色ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.26.08",
		"content":"根据科室ID删除账户信息",
		"url":"/system/saveRoleChannel.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"portalRoleId",
				"title":"角色ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"menuIds",
				"title":"频道ID字符串：",
				"placeholder":"1,2,3",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.26.09",
		"content":"根据科室ID删除账户信息",
		"url":"/system/delRoleChannel.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"userPermissionIds",
				"title":"关系ID组合:：",
				"placeholder":"1,2,3",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.26.10",
		"content":"修改密码",
		"url":"/system/updatePass.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"newPass",
				"title":"新密码",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.27.01",
		"content":"更新个人银行卡信息",
		"url":"/system/updateBank.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"bankName",
				"title":"银行名称",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"accountName",
				"title":"银行卡主姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"accountNumber",
				"title":"卡号",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.27.02",
		"content":"增加版本信息",
		"url":"/system/addVersion.htm",
		"param":[
			{
				"name":"versionCode",
				"title":"版本号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"versionName",
				"title":"版本名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"content",
				"title":"版本更新内容",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"force",
				"title":"是否强制更新",
				"placeholder":"0不强制 1强制",
				"isRequired":false
			},{
				"name":"downloadUrl",
				"title":"下载地址",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"type",
				"title":"a天使导医 b 导医管理中心",
				"placeholder":"a天使导医 b 导医管理中心",
				"isRequired":false
			}
		]
	},
	{
		"code":"F00.00.27.03",
		"content":"版本更新",
		"url":"/system/getVersion.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.27.04",
		"content":"注册JPUSH",
		"url":"/system/updateJpush.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"type",
				"title":"安卓或者苹果",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registrationID",
				"title":"机器码",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.27.05",
		"content":"获取手机验证码",
		"url":"/system/getPhoneCode.htm",
		"param":[
			{
				"name":"mobile",
				"title":"手机号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"code",
				"title":"验证码",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.27.06",
		"content":"保存商务人士信息：id为空是新增，否则为修改",
		"url":"/system/saveInternalInfo.htm",
		"param":[
		    {
		         "name":"token",
		         "title":"用户口令",
		         "placeholder":"",
		         "isRequired":true
		         },
			{
				"name":"id",
				"title":"商务人士ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"姓名",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"mobile",
				"title":"手机号",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"email",
				"title":"邮箱",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"status",
				"title":"状态",
				"placeholder":"0正常1失效",
				"isRequired":false
			}
		]
	},
	{
		"code":"F00.00.27.07",
		"content":"根据商务人士ID删除信息",
		"url":"/system/delInternalInfo.htm",
		"param":[
		         {
		        	 "name":"token",
		        	 "title":"用户口令",
		        	 "placeholder":"",
		        	 "isRequired":true
		         },
			{
				"name":"id",
				"title":"商务人士ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},
	{
		"code":"F00.00.28.01",
		"content":"查看当前用户是否绑定手机",
		"url":"/wechat/checkUserPhone.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.28.02",
		"content":"给当前用户发送验证码",
		"url":"/wechat/sendCode.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.28.03",
		"content":"绑定手机与修改信息",
		"url":"/wechat/buildingPhone.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"mobile",
				"title":"用户手机号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"code",
				"title":"验证码",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"用户姓名",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.28.04",
		"content":"更新患者信息",
		"url":"/wechat/updateUserByWx.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"name",
				"title":"患者姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"gender",
				"title":"性别",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"age",
				"title":"年龄",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.01",
		"content":"参数为医生名称，关联查询出有这个医生的医院列表",
		"url":"/wechat/getHospitalListByDocName.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"provId",
				"title":"省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"latitude",
				"title":"纬度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"longitude",
				"title":"经度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"名称",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"sort",
				"title":"排列方式",
				"placeholder":"距离最近 favourite 收藏最多 order 就诊最多",
				"isRequired":false
			},{
				"name":"organizationType",
				"title":"医院类型",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"medicalInsurance",
				"title":"是否医保",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.02",
		"content":"参数为医院名称，关联查询出有这个医生的医院列表",
		"url":"/wechat/getHospitalListByName.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"provId",
				"title":"省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"latitude",
				"title":"纬度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"longitude",
				"title":"经度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"名称",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"sort",
				"title":"排列方式",
				"placeholder":"距离最近 favourite 收藏最多 order 就诊最多",
				"isRequired":false
			},{
				"name":"organizationType",
				"title":"医院类型",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"medicalInsurance",
				"title":"是否医保",
				"placeholder":"0是1不是",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.03",
		"content":"参数为科室名称，关联查询出有这个科室的医院列表",
		"url":"/wechat/getHospitalListByDepName.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"provId",
				"title":"省",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"cityId",
				"title":"市",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"latitude",
				"title":"纬度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"longitude",
				"title":"经度",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"name",
				"title":"名称",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"sort",
				"title":"排列方式",
				"placeholder":"距离最近 favourite 收藏最多 order 就诊最多",
				"isRequired":false
			},{
				"name":"organizationType",
				"title":"医院类型",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"medicalInsurance",
				"title":"是否医保",
				"placeholder":"0是1不是",
				"isRequired":false
			},{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.04",
		"content":"根据查询条件查询医院省市列表",
		"url":"/hospital/provAndCityList.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.29.05",
		"content":"根据查询条件查询医院信息及其分佣信息",
		"url":"/wechat/hospitalInfo.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"医院ID",
				"placeholder":"当ID不存在时或从token中获取当前医院",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.06",
		"content":"查询科室列表:当医院端使用该接口时不需要输入医院ID，系统会从token中取出医院信息",
		"url":"/wechat/departList.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"organizationId",
				"title":"医院ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.07",
		"content":"根据科室ID等查询条件查询医生列表",
		"url":"/wechat/doctorList.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"departmentId",
				"title":"科室ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.08",
		"content":"根据医生ID条件查询医生详细信息",
		"url":"/wechat/doctorInfo.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"医生id",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.09",
		"content":"排班列表查询",
		"url":"/wechat/workInfoList.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"departmentId",
				"title":"科室Id",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorId",
				"title":"医生Id",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.10",
		"content":"新增预约信息",
		"url":"/wechat/saveOrder.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"organizationId",
				"title":"医院ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"departmentId",
				"title":"科室ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"shiftPlanId",
				"title":"排班ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"shiftPeriodId",
				"title":"排班时间ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorId",
				"title":"医生Id",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientName",
				"title":"患者姓名",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientMobile",
				"title":"手机号",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientGender",
				"title":"性别",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"patientAge",
				"title":"年龄",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"registerDate",
				"title":"预约时间",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.29.11",
		"content":"根据预约ID取消预约信息",
		"url":"/wechat/cancelOrder.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"registrationId",
				"title":"预约ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.30.01",
		"content":"根据查询条件查询资讯列表",
		"url":"/wechat/informationList.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.30.02",
		"content":"根据咨询ID更新阅读数量",
		"url":"/wecaht/updateInformationRead.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"资讯ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.30.03",
		"content":"分享文章获取积分",
		"url":"/wechat/shareInteg.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.31.01",
		"content":"根据openId获取个人信息",
		"url":"/wechat/getUserInfo.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.34.01",
		"content":"获取账单列表",
		"url":"/wechat/getOrderList.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			}
		]
	},{
		"code":"F00.00.34.02",
		"content":"增加医院评价信息",
		"url":"/wechat/addEvaluateInfo.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"organizationId",
				"title":"医院ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"medicalRecordId",
				"title":"预约Id",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorId",
				"title":"医生ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"organizationScore",
				"title":"医院得分",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"doctorScore",
				"title":"医生得分",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"evaluationLabels",
				"title":"评价标签",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"evaluationContent",
				"title":"评价内容",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"images",
				"title":"文件组合",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.34.03",
		"content":"根据评价id查看评价信息详情",
		"url":"/wechat/evaluateInfo.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"patientEvaluationId",
				"title":"评价id",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.34.04",
		"content":"增加反馈信息",
		"url":"/wechat/addFeedback.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"medicalRecordId",
				"title":"预约ID",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"feedbackLabels",
				"title":"反馈标签",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"feedbackContent",
				"title":"反馈内容",
				"placeholder":"",
				"isRequired":false
			},{
				"name":"images",
				"title":"文件组合",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.34.05",
		"content":"查看反馈详情",
		"url":"/operate/feedbackInfo.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信ID",
				"placeholder":"",
				"isRequired":true
			},{
				"name":"id",
				"title":"咨询ID",
				"placeholder":"",
				"isRequired":false
			}
		]
	},{
		"code":"F00.00.35.01",
		"content":"获取导医医生记录",
		"url":"/wechat/getDealDocPager.htm",
		"param":[
			{
				"name":"openId",
				"title":"微信Id",
				"placeholder":"",
				"isRequired":true
			},
			{
				"name":"pageSize",
				"title":"每页显示多少条",
				"placeholder":"",
				"isRequired":false
			},
			{
				"name":"pageIndex",
				"title":"第几页",
				"placeholder":"",
				"isRequired":false
			}
		]
	},
	{
		"code":"F00.00.36.01",
		"content":"获取个人积分信息",
		"url":"/integral/getAccumulatePoints.htm",
		"param":[
			{
				"name":"token",
				"title":"用户口令",
				"placeholder":"",
				"isRequired":true
			}
		]
	}
	
]